ALL_EXAMPLES = [
    ("Spend $50, get a free mug.", "free_gift"),
    ("Spend $120 and receive a free backpack.", "free_gift"),
    ("Get a free journal when you spend $75.", "free_gift"),
    ("Spend $200 and take home a free duffel bag.", "free_gift"),
    ("Spend $250 to unlock a free blender.", "free_gift"),
    ("Free sunglasses for spending $100.", "free_gift"),
    ("Spend $40 and receive a free water bottle.", "free_gift"),
    ("Get a free wine opener with $90 spend.", "free_gift"),
    ("Spend $150 to receive a free coffee set.", "free_gift"),
    ("Unlock a free travel pouch when you spend $200.", "free_gift"),
    ("Free cutting board when you spend $80.", "free_gift"),
    ("Earn a free tote bag for $100 spend.", "free_gift"),
    ("Spend $60 to get a free scarf.", "free_gift"),
    ("Spend $180 and get a free picnic basket!", "free_gift"),
    ("Receive a free umbrella if you spend $250.", "free_gift"),
    ("Spend €100, get a free backpack.", "free_gift"),
    ("Spend £50 and receive a free tote bag.", "free_gift"),
    ("Get free sunglasses with ₹5000 spend.", "free_gift"),
    ("Spend €75 and claim a free coffee maker.", "free_gift"),
    ("Spend £200 to unlock a free picnic blanket.", "free_gift"),
    ("Receive a free wine opener for €120 spend.", "free_gift"),
    ("Spend ₹8000 to claim a free coffee grinder.", "free_gift"),
    ("Spend AUD 150 and take home a free duffel bag.", "free_gift"),
    ("Free water bottle when spending INR 4000.", "free_gift"),
    ("Spend AUD 250 and earn a free cooler bag.", "free_gift"),
    ("Receive a free diary for spending €50.", "free_gift"),
    ("Spend £75 to get a free scarf.", "free_gift"),
    ("Unlock a free lunchbox with ₹3000 spend.", "free_gift"),
    ("Free picnic basket for spending AUD 200.", "free_gift"),
    ("Buy 5 items, get a free tote bag.", "free_gift"),
    ("Grab a free water bottle with 3 items purchased.", "free_gift"),
    ("Buy 8 products and take home a free scarf.", "free_gift"),
    ("Purchase 10 items to unlock a free mug.", "free_gift"),
    ("Free sunglasses when you buy 6 products.", "free_gift"),
    ("Add 4 items to your cart and earn a free umbrella.", "free_gift"),
    ("Buy 7 items and claim a free travel pouch.", "free_gift"),
    ("Purchase 3 products to earn a free journal.", "free_gift"),
    ("Add 5 items, receive a free wine opener.", "free_gift"),
    ("Buy 9 products and get a free backpack.", "free_gift"),
    ("Free duffel bag for buying 12 items!", "free_gift"),
    ("Unlock a free diary by buying 5 products.", "free_gift"),
    ("Buy 4 gifts and receive a free picnic blanket.", "free_gift"),
    ("Pick 6 products, get a free lunchbox.", "free_gift"),
    ("Buy 5 shirts to receive a free water bottle.", "free_gift"),
    ("Grab 3 hats and earn a free tote bag.", "free_gift"),
    ("Buy 4 items from the holiday collection, earn a free scarf.", "free_gift"),
    ("Get a free journal with 3 purchases from the summer collection.", "free_gift"),
    ("Buy any 6 products from the seasonal sale to receive a free mug.", "free_gift"),
    ("Pick 5 items from the winter collection to unlock a free coffee set.", "free_gift"),
    ("Purchase 3 items from our new arrivals and earn a free umbrella.", "free_gift"),
    ("Grab 5 products from the men’s collection and claim a free travel pouch.", "free_gift"),
    ("Buy 7 products from our home decor section, get a free picnic basket.", "free_gift"),
    ("Buy 4 items from the gift shop and receive a free wine opener.", "free_gift"),
    ("Purchase 5 products from the sale category and unlock a free blender.", "free_gift"),
    ("Free water bottle with 3 items from activewear.", "free_gift"),
    ("Add 4 products from the kitchen collection, get a free diary.", "free_gift"),
    ("Buy 2 luxury items to get a free lunchbox.", "free_gift"),
    ("Spend $100 in the clearance section to receive a free water bottle.", "free_gift"),
    ("Get a free journal when spending $200 in home decor.", "free_gift"),
    ("Spend $150 in the fashion category and claim a free tote bag.", "free_gift"),
    ("Earn a free scarf by spending $75 in accessories.", "free_gift"),
    ("Spend $250 in the travel section to take home a free duffel bag.", "free_gift"),
    ("Get a free umbrella for $100 spend in electronics.", "free_gift"),
    ("Spend $80 in the kids collection and receive a free picnic basket.", "free_gift"),
    ("Unlock a free wine opener when you spend $150 in kitchenware.", "free_gift"),
    ("Spend $120 in the outdoor gear collection to get a free cooler bag.", "free_gift"),
    ("Receive a free blender for spending $200 in appliances.", "free_gift"),
    ("Spend $90 in the wellness category, get a free lunchbox.", "free_gift"),
    ("Buy 3 hats and receive a free tote bag.", "free_gift"),
    ("Purchase 5 mugs and get a free coffee grinder.", "free_gift"),
    ("Buy 2 jackets and take home a free scarf.", "free_gift"),
    ("Free umbrella when you buy 4 backpacks.", "free_gift"),
    ("Grab 3 dresses and claim a free journal.", "free_gift"),
    ("Purchase 6 water bottles and earn a free wine opener.", "free_gift"),
    ("Buy 8 snack packs and get a free cooler bag.", "free_gift"),
    ("Earn a free blender when you buy 3 mixers.", "free_gift"),
    ("Purchase 5 pairs of socks to unlock a free lunchbox.", "free_gift"),
    ("Receive a free backpack for buying 4 t-shirts.", "free_gift"),
    ("Logged-in members: Spend $150 to receive a free scarf.", "free_gift"),
    ("VIP customers: Unlock a free wine opener with 4 items.", "free_gift"),
    ("Gold members get a free mug for $100 spend.", "free_gift"),
    ("Logged-in shoppers: Earn a free picnic basket after spending $200.", "free_gift"),
    ("Wholesale buyers: Buy 6 products, earn a free umbrella.", "free_gift"),
    ("VIP customers: Spend $250 to receive a free duffel bag.", "free_gift"),
    ("US shoppers: Earn a free water bottle for $75 spend.", "free_gift"),
    ("Gold members: Buy 4 items, get a free travel pouch.", "free_gift"),
    ("Wholesale buyers: Receive a free blender with $150 spend.", "free_gift"),
    ("Logged-in users: Buy 3 items to claim a free lunchbox.", "free_gift"),
    ("UK members: Spend £90 to unlock a free picnic blanket.", "free_gift"),
    ("Wholesale buyers: Add 5 items to earn a free cooler bag.", "free_gift"),
    ("VIP shoppers: Get a free diary with $80 spend.", "free_gift"),
    ("AU customers: Spend AUD 200 to receive a free wine opener.", "free_gift"),
    ("Gold members: Buy 6 hats, get a free journal.", "free_gift"),
    ("Logged-in shoppers: Earn a free tote bag for $120 spend.", "free_gift"),
    ("Buy one pair of jeans, get another pair free.", "buy_x_get_y"),
    ("Purchase one lipstick, and we'll throw in a second one for free!", "buy_x_get_y"),
    ("BOGO: Buy a coffee mug, get the second mug at no extra cost.", "buy_x_get_y"),
    ("Buy 2 shirts and get the cheapest one free.", "buy_x_get_y"),
    ("Grab any three items, and the lowest-priced one is free.", "buy_x_get_y"),
    ("Buy 3 dresses, and one of them will be free!", "buy_x_get_y"),
    ("Buy a pair of boots and get a free leather belt.", "buy_x_get_y"),
    ("Purchase a laptop and receive a wireless mouse complimentary.", "buy_x_get_y"),
    ("Buy a pack of markers, get a sketchpad free!", "buy_x_get_y"),
    ("Buy a bag of dog food, and get free dog treats with it.", "buy_x_get_y"),
    ("Buy a winter jacket, and get 20% off on any scarf.", "buy_x_get_y"),
    ("Grab a pair of sunglasses, and enjoy 15% off on a hat.", "buy_x_get_y"),
    ("Buy a smartphone and get 25% off on the wireless charger.", "buy_x_get_y"),
    ("Purchase one skincare product, and get 10% off on any face cleanser.", "buy_x_get_y"),
    ("Buy from our summer footwear collection and get 30% off on handbags.", "buy_x_get_y"),
    ("Shop from the home decor section and get 20% off on kitchen accessories.", "buy_x_get_y"),
    ("Purchase any item from the electronics section to unlock 25% off fitness gadgets.", "buy_x_get_y"),
    ("Buy products from the toy category and get 15% off board games.", "buy_x_get_y"),
    ("Buy 5 items, and get 10% off on the 6th item in your cart.", "buy_x_get_y"),
    ("Purchase any 4 items, and we'll take 20% off the 5th item automatically.", "buy_x_get_y"),
    ("Add 7 items to your cart and receive the 8th item for free.", "buy_x_get_y"),
    ("Buy 10 products and get the next item with a 50% discount.", "buy_x_get_y"),
    ("Spend $50 and get 20% off on a wireless speaker.", "buy_x_get_y"),
    ("Hit a total of €100 and unlock 30% off on select headphones.", "buy_x_get_y"),
    ("Spend 75 GBP and get 40% off a premium watch.", "buy_x_get_y"),
    ("Spend 5000 INR and enjoy 25% off on a luxury travel bag.", "buy_x_get_y"),
    ("Spend 150 AUD to qualify for 50% off a barbecue grill.", "buy_x_get_y"),
    ("Buy two items and get a free product—exclusive to Gold tier members.", "buy_x_get_y"),
    ("VIP customers: Buy any 3 products and get the cheapest one free.", "buy_x_get_y"),
    ("For student members: Spend $40 and get 20% off on backpacks.", "buy_x_get_y"),
    ("Market-exclusive offer: Buy 1 jacket, get 1 scarf free in Australia.", "buy_x_get_y"),
    ("Buy one sofa, get another sofa for free!", "buy_x_get_y"),
    ("BOGO: Purchase any sneakers, and the second pair is free.", "buy_x_get_y"),
    ("Buy one T-shirt, get another T-shirt free.", "buy_x_get_y"),
    ("Grab 4 novels and the cheapest one is free!", "buy_x_get_y"),
    ("Buy any 3 toys, and get the lowest-priced toy absolutely free.", "buy_x_get_y"),
    ("Buy 6 stationery items, and one of them will be free!", "buy_x_get_y"),
    ("Purchase a guitar and get a free set of strings.", "buy_x_get_y"),
    ("Buy a coffee machine and get a free coffee bean pack included.", "buy_x_get_y"),
    ("Buy 2 perfumes and receive a free scented candle.", "buy_x_get_y"),
    ("Buy one camera and get the camera bag for free.", "buy_x_get_y"),
    ("Buy a smartwatch, and enjoy 25% off on fitness bands.", "buy_x_get_y"),
    ("Grab a coat, and avail 15% off on matching gloves.", "buy_x_get_y"),
    ("Buy any shirt and unlock 10% off on trousers.", "buy_x_get_y"),
    ("Purchase a tablet, and get 20% off on protective cases.", "buy_x_get_y"),
    ("Shop from the kitchenware range and get 25% off the dining collection.", "buy_x_get_y"),
    ("Buy from the sports apparel section and get 20% off gym bags.", "buy_x_get_y"),
    ("Select items from our gardening tools and unlock discounts on outdoor furniture.", "buy_x_get_y"),
    ("Shop from our art supplies range and enjoy 10% off sketchbooks.", "buy_x_get_y"),
    ("Add 3 products to your cart and the 4th item is free.", "buy_x_get_y"),
    ("Get 20% off your 5th item when purchasing 4 or more products.", "buy_x_get_y"),
    ("Buy 8 items and get the 9th item complimentary.", "buy_x_get_y"),
    ("Purchase 12 products and get the 13th product at half price.", "buy_x_get_y"),
    ("Spend $70 and get 15% off on a premium wallet.", "buy_x_get_y"),
    ("Spend €150 and unlock 25% off on designer sunglasses.", "buy_x_get_y"),
    ("Spend 200 GBP and get 35% off on a branded jacket.", "buy_x_get_y"),
    ("Spend 8000 INR and enjoy 30% off on a luxury watch.", "buy_x_get_y"),
    ("Spend 200 AUD and qualify for 20% off a portable cooler.", "buy_x_get_y"),
    ("Exclusive for Silver tier: Buy any 5 products and get the cheapest one free.", "buy_x_get_y"),
    ("Loyalty members: Spend $100 and get 25% off select shoes.", "buy_x_get_y"),
    ("For first-time buyers: Buy one accessory, get one free.", "buy_x_get_y"),
    ("Buy 2 dresses, and the third dress is free for VIP customers.", "buy_x_get_y"),
    ("Buy one pair of running shoes, get another pair at no cost!", "buy_x_get_y"),
    ("BOGO: Purchase one hardcover book, get the second free!", "buy_x_get_y"),
    ("Buy one toy car, get another toy car free.", "buy_x_get_y"),
    ("Buy 3 items, and the cheapest one is on the house.", "buy_x_get_y"),
    ("Buy 5 groceries and the lowest-priced item is free!", "buy_x_get_y"),
    ("Purchase 7 items, and one of them will be complimentary.", "buy_x_get_y"),
    ("Buy a watch and get a free strap.", "buy_x_get_y"),
    ("Buy a leather wallet, and receive a keychain for free.", "buy_x_get_y"),
    ("Buy one pair of earrings, and get a free bracelet.", "buy_x_get_y"),
    ("Buy a set of towels and get a free shower mat.", "buy_x_get_y"),
    ("Buy a gaming chair and enjoy 15% off on a gaming desk.", "buy_x_get_y"),
    ("Purchase a planner and get 10% off pens.", "buy_x_get_y"),
    ("Buy any backpack and get 20% off on a duffel bag.", "buy_x_get_y"),
    ("Buy a smartwatch, and get 20% off on earbuds.", "buy_x_get_y"),
    ("Shop from our pet accessory section and unlock discounts on bedding.", "buy_x_get_y"),
    ("Buy from the travel gear range and enjoy 15% off carry-on luggage.", "buy_x_get_y"),
    ("Select any furniture piece and unlock 20% off lighting products.", "buy_x_get_y"),
    ("Shop from the kid's wear section and get 25% off school supplies.", "buy_x_get_y"),
    ("Buy 6 items, and get 20% off on the 7th item.", "buy_x_get_y"),
    ("Add 9 items to your cart and receive the 10th item at no cost.", "buy_x_get_y"),
    ("Buy 11 products, and the 12th one comes with a discount.", "buy_x_get_y"),
    ("Spend $60 and get 10% off on a premium backpack.", "buy_x_get_y"),
    ("Spend €120 and unlock discounts on select shoes.", "buy_x_get_y"),
    ("Spend 100 GBP and get 20% off on skincare products.", "buy_x_get_y"),
    ("Spend 7000 INR and enjoy 15% off on luxury bedding.", "buy_x_get_y"),
    ("Spend 175 AUD and qualify for 25% off on a gym mat.", "buy_x_get_y"),
    ("Gold tier members: Buy 3 shirts and get a free accessory.", "buy_x_get_y"),
    ("Student offer: Spend $80 and get 10% off on a backpack.", "buy_x_get_y"),
    ("Exclusive for Australian buyers: Buy a pair of sandals, get a free hat.", "buy_x_get_y"),
    ("Buy 2 items and get 10% off, buy 4 items for 20% off your entire cart!", "tiered_discount"),
    ("Enjoy tiered cart savings: 2 items = 10% off, 3 items = 15%, 5+ items = 25%.", "tiered_discount"),
    ("Spend $50 for 5% off and $100 for 10% off your cart!", "tiered_discount"),
    ("Discount tiers: €50 gets you 10% off, €100 unlocks 20% off!", "tiered_discount"),
    ("Save $10 when you spend $75, save $25 when you spend $150!", "tiered_discount"),
    ("Get $5 off when you buy 2 items, $15 off for buying 5 items!", "tiered_discount"),
    ("Collection promo: Buy 2 shirts to get 10% off, buy 4 to unlock 20%.", "tiered_discount"),
    ("Exclusive member offer: Spend $50 for 10% off, $100 for 20%.", "tiered_discount"),
    ("Tiered savings: 2 products = 5% off, 4 products = 15%.", "tiered_discount"),
    ("Purchase 3 items for 10% off, grab 6 for 20% off storewide!", "tiered_discount"),
    ("Buy more, save more: Spend $100 for 10% off, hit $200 for 15%.", "tiered_discount"),
    ("Deals: £50 spent gets you 5% off, £100 unlocks 10%, £150 gets 20% off.", "tiered_discount"),
    ("Step up your savings: Spend $50 for $5 off, spend $150 to save $25.", "tiered_discount"),
    ("Get $10 off for purchasing 3 items, $30 off if you buy 6 items!", "tiered_discount"),
    ("Take 10% off 2+ jackets, 20% off 4+ jackets.", "tiered_discount"),
    ("VIP only: Spend $100 for 10% off your cart, $250 for 25%.", "tiered_discount"),
    ("Shop more, save more: 3 items = 10% off, 7 items = 20%.", "tiered_discount"),
    ("Buy 2 products, save 10%. Buy 4 products, enjoy 25% off.", "tiered_discount"),
    ("Spend $50 for 5% off all purchases. Spend $200 for 20%.", "tiered_discount"),
    ("Limited-time savings: €25 spent yields 5% off, €75 gets 15%.", "tiered_discount"),
    ("Save $10 when spending $60 or $30 when you hit $150.", "tiered_discount"),
    ("Buy 2 pieces for $5 off, buy 5 pieces for $20 off!", "tiered_discount"),
    ("Shoes promo: 3 pairs = 10% off, 6 pairs = 25%.", "tiered_discount"),
    ("Shop tiered discounts: Spend $100 for 10%, $250 for 20%.", "tiered_discount"),
    ("Cart savings: Add 2 items for 10% off, 4 items for 20%.", "tiered_discount"),
    ("Subtotal tiers: $50 = 5% off, $150 = 15%, $300 = 25% off!", "tiered_discount"),
    ("Savings for £30 spent is 5%, £80 spent saves you 20% on all.", "tiered_discount"),
    ("Spend INR 1,500 for INR 150 off, spend INR 5,000 for INR 500 off.", "tiered_discount"),
    ("Buy 2 items for $5 off, 6 items for $25 off your cart total.", "tiered_discount"),
    ("Summer sale: 10% off 2+ skirts, 20% off 5+ skirts.", "tiered_discount"),
    ("Exclusive: Spend AUD $100 for 10%, AUD $300 for 25%!", "tiered_discount"),
    ("Bulk buy savings: 2 items saves 7%, 5 items saves 20%.", "tiered_discount"),
    ("Spend $75 to save 5%, $150 unlocks 10%, $300 for 20% savings.", "tiered_discount"),
    ("Cart subtotal tiers: €50 = 10% off, €150 = 25% off.", "tiered_discount"),
    ("Shop big: Spend £30 for £3 off, spend £100 for £15 off.", "tiered_discount"),
    ("Get $2 off for 2+ books, 15% off 10+ books.", "tiered_discount"),
    ("Member-only: Spend INR 3,000 for 10%, INR 8,000 for 25%.", "tiered_discount"),
    ("Save big: Buy 3 items for 10% off, buy 8 items for 25%.", "tiered_discount"),
    ("Earn savings: $100 in your cart saves 10%, $300 saves 25%.", "tiered_discount"),
    ("Special: €25 spend = €3 off, €100 = €20 off.", "tiered_discount"),
    ("Buy 2 for $10 off, buy 5 for $30 off your cart!", "tiered_discount"),
    ("Kids' collection: Buy 2 toys for 5% off, buy 4 toys for 15%.", "tiered_discount"),
    ("VIP discount tiers: Spend $200 for 10%, $500 for 30%!", "tiered_discount"),
    ("Shop and save more: 3+ items saves 10%, 6+ saves 25%!", "tiered_discount"),
    ("Spend $50 to unlock 5% off, $125 unlocks 15%, $250 for 25%.", "tiered_discount"),
    ("Tiered promo: £50 = 10% off, £150 = 25%.", "tiered_discount"),
    ("Spend INR 1,000 for INR 100 off, spend INR 5,000 for INR 500.", "tiered_discount"),
    ("Get $5 off for buying 2 pens, $25 off for buying 6 pens.", "tiered_discount"),
    ("Spend AUD $50 for 5% off, AUD $200 for 20% off!", "tiered_discount"),
    ("Quantity tiers: 2 pairs = 10% off, 5 pairs = 20%.", "tiered_discount"),
    ("Customer exclusive: Spend $80 for 8% off, $300 for 25%.", "tiered_discount"),
    ("Tiered collection deal: Buy 2 hats, save 5%; buy 4 hats, save 20%!", "tiered_discount"),
    ("Spend INR 3,500 for INR 250 off, spend INR 10,000 for INR 1,000.", "tiered_discount"),
    ("Get 10% off 3 or more mugs, 25% off 6 or more mugs.", "tiered_discount"),
    ("Spend $100 saves you 8%, spend $300 saves you 20%.", "tiered_discount"),
    ("Save €10 for spending €75, save €25 for spending €200.", "tiered_discount"),
    ("Buy 3 umbrellas for $5 off, buy 6 umbrellas for $20 off.", "tiered_discount"),
    ("Spend AUD $50 for AUD $5 off, AUD $150 for AUD $30 off.", "tiered_discount"),
    ("Shop more scarves: 2 = 8% off, 5 = 20% off!", "tiered_discount"),
    ("Unlock savings: Spend £100 for 10%, £250 for 25% off!", "tiered_discount"),
    ("Special: €25 saves 10%, €100 saves 20%, €200 saves 30%!", "tiered_discount"),
    ("Buy 2 T-shirts for $10 off, buy 8 for $35 off the cart!", "tiered_discount"),
    ("Spend INR 2,000 = INR 100 off, INR 6,000 = INR 400 off.", "tiered_discount"),
    ("Get 5% off 2+ shoes, get 20% off 5+ shoes!", "tiered_discount"),
    ("Spend $125 = 10% off, spend $300 = 25% off!", "tiered_discount"),
    ("Collection-wide sale: Spend €50 for 10% off, €150 for 25% off.", "tiered_discount"),
    ("Buy 2 for $5 off, buy 10 for $30 off your total!", "tiered_discount"),
    ("Get INR 500 off a INR 10,000 spend, INR 1000 off a INR 20,000 spend.", "tiered_discount"),
    ("Save 10% buying 3 jackets, save 25% when buying 6.", "tiered_discount"),
    ("Spend AUD $150 = AUD $15 off, spend AUD $450 = AUD $50 off.", "tiered_discount"),
    ("Tiered customer discount: Spend £50 = 5% off, £150 = 20% off.", "tiered_discount"),
    ("Buy 2 belts for $5 off, get $25 off for buying 8 belts!", "tiered_discount"),
    ("Spend INR 4,000 to save INR 200, spend INR 10,000 to save INR 600.", "tiered_discount"),
    ("Spend €100 for 10% off all shoes, spend €250 for 25% off!", "tiered_discount"),
    ("Cart tiers: 3 shirts = 10% off, 7 shirts = 25% off.", "tiered_discount"),
    ("Spend $120 = $12 off, spend $400 = $50 off your cart!", "tiered_discount"),
    ("Spend INR 2,000 = INR 150 off, spend INR 8,000 = INR 800 off.", "tiered_discount"),
    ("Save 7% when buying 4 mugs, save 15% on 12 mugs!", "tiered_discount"),
    ("Spend AUD $75 = AUD $5 off, spend AUD $250 = AUD $30 off.", "tiered_discount"),
    ("Buy 3 pieces = 10% off, buy 9 pieces = 30% off.", "tiered_discount"),
    ("Get £3 off a £50 spend, get £20 off a £150 spend!", "tiered_discount"),
    ("Spend INR 5,000 saves INR 500, spend INR 15,000 saves INR 1,500.", "tiered_discount"),
    ("Save 15% for buying 4 hats, save 25% for buying 10 hats.", "tiered_discount"),
    ("Spend AUD $300 = AUD $20 off, AUD $750 = AUD $70 off.", "tiered_discount"),
    ("Get 10% off when you purchase 2+ products from our accessories collection.", "tiered_discount"),
    ("Spend £200 on handbags and save £20, spend £400 and save £50.", "tiered_discount"),
    ("Buy 3 items = $10 off, buy 8 items = $35 off your collection!", "tiered_discount"),
    ("Spend INR 1,500 saves INR 300, spend INR 6,000 saves INR 1,200.", "tiered_discount"),
    ("Save 8% for 4+ items in the winter collection, save 15% for 10+ items!", "tiered_discount"),
    ("Spend AUD $50 = AUD $5 off, AUD $200 = AUD $20 off.", "tiered_discount"),
    ("Purchase 5 items to unlock 15%, purchase 10 to unlock 30% off!", "tiered_discount"),
    ("Run a flash sale this weekend!", "unsupported"),
    ("Can we offer loyalty points to our customers?", "unsupported"),
    ("Give everyone 50% off this Friday night.", "unsupported"),
    ("What discounts should we give to first-time buyers?", "unsupported"),
    ("Give 200% off for all items!", "unsupported"),
    ("Hello, how are you?", "unsupported"),
    ("Buy stuff and get some reward.", "unsupported"),
    ("How many users visited our store last week?", "unsupported"),
    ("Set up a referral program for our products.", "unsupported"),
    ("Run a sale next Wednesday.", "unsupported"),
    ("Offer free shipping on all orders.", "unsupported"),
    ("Create a special discount for subscribers.", "unsupported"),
    ("Spend $0 and get free stuff!", "unsupported"),
    ("Can you help with my marketing campaign?", "unsupported"),
    ("Buy some items and unlock something cool.", "unsupported"),
    ("Export analytics for the past 3 months.", "unsupported"),
    ("Give away coupon codes!", "unsupported"),
    ("Run a flash sale every Monday morning.", "unsupported"),
    ("Offer free shipping worldwide!", "unsupported"),
    ("What discounts apply to my subscription customers?", "unsupported"),
    ("Spend -1 dollars and receive 10% off.", "unsupported"),
    ("What time does the store open?", "unsupported"),
    ("Buy things and get a special gift.", "unsupported"),
    ("Show me the sales figures for last month.", "unsupported"),
    ("Introduce a referral discount system.", "unsupported"),
    ("Start a 24-hour flash sale.", "unsupported"),
    ("Create free shipping promotions.", "unsupported"),
    ("Offer discounts for new subscribers.", "unsupported"),
    ("Give everyone negative 100 dollars off.", "unsupported"),
    ("What’s your favorite promotion?", "unsupported"),
    ("Give customers something free after buying things.", "unsupported"),
    ("Add new categories to the store.", "unsupported"),
    ("How about referral bonuses for customers?", "unsupported"),
    ("Host a flash sale tomorrow.", "unsupported"),
    ("Make shipping free if people spend any amount.", "unsupported"),
    ("Discount first-time customers by 15%.", "unsupported"),
    ("Spend less than zero money to earn rewards.", "unsupported"),
    ("Hello, can you set up a sale?", "unsupported"),
    ("Buy products and customers will be rewarded somehow.", "unsupported"),
    ("Analyze performance by region.", "unsupported"),
    ("Run ads for coupons on social media.", "unsupported"),
    ("Create a flash sale for next week’s holiday.", "unsupported"),
    ("Offer free delivery for orders over $50.", "unsupported"),
    ("Reward new customers with exclusive discounts.", "unsupported"),
    ("$0 spend triggers free gifts!", "unsupported"),
    ("Hi, what are current promo trends?", "unsupported"),
    ("Buy items and unlock some kind of reward.", "unsupported"),
    ("Adjust product pricing based on demand.", "unsupported"),
    ("Can we give free coupons to our mailing list subscribers?", "unsupported"),
    ("Host a 3-day sale next weekend.", "unsupported"),
    ("Start a free shipping campaign for international orders.", "unsupported"),
    ("Set up discounts for subscription renewals.", "unsupported"),
    ("Offer 500% off for spending $10.", "unsupported"),
    ("What’s happening today in the store?", "unsupported"),
    ("Buy things and get something extra.", "unsupported"),
    ("Build a report on customer buying trends.", "unsupported"),
    ("Can we enable referral links for product discounts?", "unsupported"),
    ("Run a flash sale for 10 hours only.", "unsupported"),
    ("Provide free shipping to customers who use coupons.", "unsupported"),
    ("Discount customers who subscribe before the weekend.", "unsupported"),
    ("Discount items by 300% — impossible!", "unsupported"),
    ("What’s the weather today?", "unsupported"),
    ("Buy things to unlock potential rewards.", "unsupported"),
    ("Display recent top-selling products.", "unsupported"),
    ("How about coupon giveaways in email campaigns?", "unsupported"),
    ("Introduce flash sales during holidays.", "unsupported"),
    ("Free shipping for all orders above 500 INR.", "unsupported"),
    ("Offer discounts to new subscription customers.", "unsupported"),
    ("Spend $0 and get discounts!", "unsupported"),
    ("Hi, can you recommend a promo?", "unsupported"),
    ("Get rewards when buying things.", "unsupported"),
    ("Create performance dashboards for managers.", "unsupported"),
    ("Start referring discounts for customer acquisition.", "unsupported"),
    ("Run limited-time flash sales every Friday.", "unsupported"),
    ("Provide free delivery for customers spending over $100 AUD.", "unsupported"),
    ("Offer discounts for initial subscription signups.", "unsupported"),
    ("Spend -$5 to unlock free items.", "unsupported"),
    ("Hello, how can we improve promotions?", "unsupported"),
    ("Buy products and get rewarded somehow.", "unsupported"),
    ("Generate a sales report for yesterday.", "unsupported"),
    ("Offer referral discounts for brand ambassadors.", "unsupported"),
    ("Host weekend-only flash sales.", "unsupported"),
    ("Deliver products for free if the cart exceeds 150 EUR.", "unsupported"),
    ("Discount people who sign up during the event.", "unsupported"),
    ("Provide minus one discounts.", "unsupported"),
    ("Hi! Can I get a discount?", "unsupported"),
    ("Buy items and receive a special prize.", "unsupported"),
    ("Export customer segmentation data.", "unsupported"),
    ("Start advertising discounts via referral links.", "unsupported"),
    ("Flash sales should happen during the evenings.", "unsupported"),
    ("Free shipping for orders greater than 300 GBP.", "unsupported"),
    ("Reward customers who join our subscription program.", "unsupported"),
    ("Spend negative dollars and earn rewards.", "unsupported"),
    ("Hello, what’s the best deal we can offer?", "unsupported"),
    ("Buy things and unlock some kind of bonus.", "unsupported"),
    ("Check inventory levels for all products.", "unsupported"),
    ("Send out coupon codes via newsletters.", "unsupported"),
    ("Host timed flash sales for the evening hours.", "unsupported"),
    ("Enable free transportation for orders over 500 GBP.", "unsupported"),
    ("What about discounts for people who subscribe annually?", "unsupported"),
    ("Spend $0 and unlock surprises.", "unsupported"),
    ("Hi, can we motivate buyers with perks?", "unsupported"),
    ("Buy things and gain undefined rewards.", "unsupported"),
    ("Create a detailed inventory tracking system.", "unsupported"),
    ("Spend ₹5000, tote free", "free_gift"),
    ("Free diary with a $75 spend", "free_gift"),
    ("Spend $80, free mug", "free_gift"),
    ("Get a free gym bag for spending over $120 on any women's sportswear collection items during this promotional period", "free_gift"),
    ("Gift with $100 purchase", "free_gift"),
    ("Spend ₹8000 and receive a leather-bound planner absolutely free with your order, valid for one week only", "free_gift"),
    ("Complimentary water bottle for spends $90+", "free_gift"),
    ("Receive a free branded pen set by spending at least £70 during this sale", "free_gift"),
    ("Free tote bag on ₹7500 spend", "free_gift"),
    ("Enjoy a complimentary cosmetic organizer if your shopping cart exceeds $110 in total value on select beauty products", "free_gift"),
    ("Buy 50 notebooks, get 10 free (INR)", "buy_x_get_y"),
    ("Purchase 100 pens, get 25 free (AUD)", "buy_x_get_y"),
    ("Wholesale: Buy 500 bottles, 50 free (₹)", "buy_x_get_y"),
    ("Buy 2 packs of socks, get 1 pair free", "buy_x_get_y"),
    ("Bulk deal: Buy 20 chairs, 5 free (AUD)", "buy_x_get_y"),
    ("Purchase 200 units of soap, get 25 free (INR)", "buy_x_get_y"),
    ("Buy 3 gardening tools, get the cheapest free", "buy_x_get_y"),
    ("Buy 10 boxes of cookies, get 2 free (₹)", "buy_x_get_y"),
    ("Wholesale: Buy 300 shirts, get 30 ties free", "buy_x_get_y"),
    ("Buy 4 handbags, get 1 wallet free (AUD)", "buy_x_get_y"),
    ("Spend ₹2000 get 5% off, ₹5000 get 10% off, ₹8000 get 15% off, ₹10000 get 20% off", "tiered_discount"),
    ("Spend AUD 50 save 5%, AUD 100 save 10%, AUD 200 save 20%, AUD 300 save 25%", "tiered_discount"),
    ("₹1500: 5% off, ₹3000: 10% off, ₹6000: 15% off, ₹9000: 20% off, ₹12000: 25% off", "tiered_discount"),
    ("Spend $300 get 5% off, $600 get 10% off, $1200 get 15% off, $2400 get 20% off, $5000 get 30% off", "tiered_discount"),
    ("AUD 100 for 10%, AUD 250 for 15%, AUD 500 for 20%, AUD 1000 for 30%", "tiered_discount"),
    ("₹1000 unlocks 5%, ₹2500 unlocks 10%, ₹4000 unlocks 15%, ₹7000 unlocks 20%", "tiered_discount"),
    ("Footwear collection: Spend ₹2000 save 5%, ₹5000 save 10%, ₹8000 save 15%, ₹12000 save 25%", "tiered_discount"),
    ("Spend INR 2000 for 10%, INR 5000 for 15%, INR 8000 for 20%, INR 12000 for 25% off on accessories", "tiered_discount"),
    ("AUD 50 for 5% off, AUD 150 for 10% off, AUD 300 for 20%, AUD 600 for 25%, AUD 1200 for 30%", "tiered_discount"),
    ("Men's collection: ₹3000 for 5%, ₹6000 for 10%, ₹10000 for 15%, ₹15000 for 25% off", "tiered_discount"),
]
